# model and training
model_name: slobert
pretrained_model: EMBEDDIA/sloberta
# pretrained_model: models/sloner
batch_size: 16
epochs: 20
lr: 0.00001
gpu_id: 0

# logging
wandb_project: ner_sta
models_path: /mnt/data/jpawlowski/university/nlp_models/

data_path: /home/jpawlowski/repos/sta-source-bias-detection/data/ner_results_combined_parsed_w_split.json

max_margin_size: 128
max_length: 128
